ethereum/remix-plugins-directory

- tools/ipfs-upload/bin/upload-remix-plugin
- tools/ipfs-upload/generateProfile.js
- tools/ipfs-upload/package-lock.json
- tools/ipfs-upload/package.json
- replace `prompt` by `inquirer`
- use `signale`
- move the profile generation away from the bin
> use inquirers and signale

- plugins/solhint/profile.json
Hi, we've been working on a basic version of a remix plugin for solhint.
This leverages the new feature of multi-highlihgting, so I think it only works in the alpha version (for now). It also shows a list of errors for the last saved file in the side panel.
We hope we can continue to add features to this. For example, we'd love to be able to show the error message in a tooltip, but I think the IDE doesn't support that right now.
> Add solhint to list of plugins

- plugins/zokrates/profile.json
Migrating zokrates plugin to netlify
> Update zokrates url in profile.json

- plugins/ethdoc-viewer/profile.json
This PR adds the viewer plugin for ethdoc v2
> ethdoc viewer plugin

- plugins/learneth/profile.json
https://github.com/bunsenstraat/remix-learneth-plugin/blob/master/CHANGELOG.md
> learneth accepting js calls from IDE

- plugins/learneth/profile.json
Reverts ethereum/remix-plugins-directory#91
> Revert "learneth accepting js calls from IDE"

- plugins/defi-explorer/profile.json
Hi,
This PR adds Defi explorer plugin :)
> added defi explorer

- common-api/compiler/type/input.ts
- common-api/compiler/type/output.ts
In support to https://github.com/ethereum/remix-project/pull/472
> legacyAST removed

- plugins/source-verifier/profile.json
> Updating sourcify to version 0.5.2

- plugins/source-verifier/profile.json
> Fixing sourcify 0.5.2

- plugins/celo/profile.json
Hello, I want to publish a plugin that can be used for the Celo's smart contracts using the Remix IDE.
> Create Celo plugin profile.json

- plugins/gas-profiler/profile.json
> added new gas profiler url

- plugins/solhint/profile.json
In an attempt to make the plugin display name, description and documentation link more clear.
> update solhint profile

- plugins/one-click-dapp/profile.json
Hello maintainers! Thanks to @bunsenstraat for letting me know about the updates here
https://github.com/oneclickdapp/remix-plugin-one-click-dapp/pull/10
Hopefully everything works well now!
> Update One Click Dapp API

- plugins/ethcode/profile.json
Ethcode plugin connector profile is included.
> Add ethcode plugin connector webview

- plugins/zokrates/profile.json
Zokrates plugin has been migrated to GitHub pages
> Update ZoKrates profile.json

- plugins/defi-tutorials/profile.json
Add tutorials and allow it to activate uma tutorials
> add defi tutorials

- plugins/source-verifier/profile.json
- fetch partial matches
- update sourcify icon
> Update Sourcify plugin

- plugins/contract-deployer/profile.json
Updating the plugin description according to your suggestion.
> fix: update contract deployer descr

- plugins/dgit/profile.json
> add repo & issue urls - not email...yet

- plugins/klaytn/profile.json
This is DEPLOY & RUN TRANSACTIONS plugin of **Klaytn** which EVM based global public blockchain project.
Klaytn Governance Council is an alliance of multinational businesses and organizations including kakao, binance, makerdao, worldpay, cocone, ozys etc..
- https://www.klaytn.com
- https://ozys.io
Thank you!
> Add Klaytn plugin metadata.

- plugins/starkNet_compiler/profile.json
same as https://github.com/ethereum/remix-plugins-directory/pull/298/files
> update startknet url

- plugins/vyper/profile.json
> upgrade vyper

- plugins/wds-code-remix/profile.json
Hello, I'm Yoonsoo Jang from Welldone Studio team from DSRV company.
I want to publish wds-code-remix with which users can deploy and execute multi chain smart contract.
Please refer to [https://docs.welldonestudio.io/code/getting-started](url)
Best regards.
> Create wds-code-remix plugin profile.json

- plugins/klaytn/profile.json
Reverts ethereum/remix-plugins-directory#352
cc @Jongsic
> Revert "Delete plugins/klaytn directory"

- plugins/zksync/profile.json
We are adding a new Remix plugin to assist in development, compilation and deployment of Solidity smart contracts for zkSync Era ecosystem:
> Descriptor for zkSync Era Remix plugin.

- plugins/buildbear/profile.json
This PR adds the `profile.json` for the [BuildBear](https://buildbear.io) plugin.
> Added BuildBear.io plugin

- plugins/defi-explorer/profile.json
- plugins/defi-tutorials/profile.json
- plugins/uma-playground/profile.json
- plugins/uma-tutorials/profile.json
Reverts ethereum/remix-plugins-directory#372
> Revert "removed unused plugins"

- plugins/cookbookdev/profile.json
fixes https://github.com/ethereum/remix-plugins-directory/issues/348
> adding repo to cookbook

- plugins/solidityscan/profile.json
This plugin provides scanning capabilities for solidity smart contracts. It allows users to scan a single .sol file, folder or an entire workspace and gives a security profile with a security score, vulnerability distribution according to criticality levels & highlights the lines of code containing the vulnerabilities.
Here is the documentation of our plugin: https://docs.solidityscan.com/remix/
> Add SolidityScan remix plugin
